### ISSUE TITLE
When trying to add new options, the selection restarts

### ISSUE THREAD

**Issue by jadelcar** [surveycto/table-list#2]
**Situation**
In our questionnaire, we have one question with type  "select_multiple" and appearance "custom-table-list(delimiter='|',headers='ID,Name,Region,Acronym'). The result of this selection is used in several other fields.

**Problem**
When you make your selection in the first run it looks okay. However, if you continue and later you try to go back and select an extra option, when you click it erases all the options you had selected before, meaning that you start afresh.

This is a bit of an inconvenience in our case, because we might be doing a selection of 5-10 items, and it's not uncommon that the enumerator need to go back to this question and add more choices, but in the current situation, every time they want o add something they need to start all over again.

We are using the result of this selection as input in other fields, and it is possible that this is what's creating the problem, so I am attaching the questionnaire definition form with the section affected by this issue.

I hope this information is enough. Please let me know if you need extra details. We are using SurveyCTO collect 2.7.

Thank you!
[select_multiple_table_bug.xlsx](https://github.com/surveycto/table-list/files/5653720/select_multiple_table_bug.xlsx)

**Comment by mofya1** [comment]
Hi @jadelcar, 

Thank you for reporting this. Just circling back to confirm that this is fixed in version 1.3.13 of the field plug-in. 

Kind regards
